# Generated by Django 3.2 on 2021-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='service_file'),
        ),
    ]
