# Generated by Django 3.2.13 on 2022-07-08 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210907_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerregistration',
            name='divison',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='create_at',
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='division',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='country',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='district',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='house_info',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='post_office_or_union',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('', 'Please Select'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Other', 'Other')], max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='upazila',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
