# Generated by Django 3.2.6 on 2021-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210907_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerregistration',
            name='divison',
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='division',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='country',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='district',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='house_info',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='post_office_or_union',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('', 'Please Select'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Other', 'Other')], max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='customerregistration',
            name='upazila',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
