# Generated by Django 3.2.13 on 2022-07-08 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20220708_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerRegistration',
            new_name='CustomUserRegistration',
        ),
    ]
