# Generated by Django 3.2.13 on 2022-07-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserregistration',
            name='work_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area'),
        ),
    ]
